language: python
python:
  - '3.6'

install:
  - npm install -g firebase-tools

script:
  - python generate.py
  - find public

deploy:
  skip_cleanup: true
  edge: true
  on:
    branch: master
  provider: firebase
  token:
    secure: "0RZFU2m4GE7LSHySgbrrqLiPkwmueha49/jMtyS4AVUIb3SNKXw+ogb9PMT9C11VaBoTjb5TrC/eVDlx8u8fLFfsWdIYrJLOfrelasO5i9d9Sa9EyAnXUskuGAi52k9A1/m7VPwfEKq1ERMa8TItcrXrT5sFvbVZDSk7roZu2xSy/MyFWdNyJaTSMhJNg6o9ZM/GMqbAnJjK1/INrI1xjye3EtZNWAUNhhLf0VlJGzkNw9m/L4ucsR6myVCuFsN7VSDLp3gPYJdWWolr4ba/mS052nmTJysNpvGpoK8w6UcL9i62bkgrmQi4rf9k6SFtYce9aryV42TD4n3d+f022hYb8EMb3lDcgxy5H5pCasfH9+1XiO3JO1zN2dM+co3ebLzl9gsfTDCyU9qgD81MhYaKcw/+VKpkvkevoXWBQEZqwLKyEEaKd5xfYkBlHm0e23TL8aNg8EYnoCjv+KCV/a/iMt/4Ew8DR8f49oqQjGJFP49wIh8TDwrJov6pbcSiznHzqSn0Wt+XbFG28R5HG7y8e2WeUmgeGNbEuSPFViCb4W0dvmD2ijSzL3c7DaPOMKwe8mO6wzlHnMDDYpNw4kgIfQACDdXib2RL2qQLFDBuLhok94MgcWlWdk7Zs/JHG9hw5r/RipWIgiacfxOmspxRz9o6RNDSyOXA9t3qkIk="
  message: "Build: $TRAVIS_JOB_NUMBER, commit: $TRAVIS_COMMIT_MESSAGE"
